namespace BlazorBootstrap;

/// <summary>
/// Defines the commands available in a <see cref="RichTextEditor" /> toolbar.
/// </summary>
public enum RichTextEditorToolbarItem
{
    None,
    Print,
    Undo,
    Redo,
    Paragraph,
    Heading1,
    Heading2,
    Heading3,
    Heading4,
    Heading5,
    Heading6,
    Caption,
    FontFamily,
    FontSize,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    Subscript,
    Superscript,
    TextColor,
    HighlightColor,
    AlignLeft,
    AlignCenter,
    AlignRight,
    AlignJustify,
    Indent,
    Outdent,
    OrderedList,
    UnorderedList,
    Link,
    Image,
    HorizontalRule,
    Table,
    Blockquote,
    CodeBlock,
    ClearFormatting,
    Fullscreen,
}
